import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'
import { CssBaseline } from '@mui/material'

// const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({subsets: ['latin'], variable: '--font-montserrat', display: 'swap'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <CssBaseline />
      <html lang="en">
        <body className={montserrat.variable}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </>
  )
}
